language: python
python:
  - "3.3"
# command to install dependencies
install:
  - pip install paramiko
  - pip install nose pylint
# command to run tests
script:
  - find . -name "*.py" | xargs pylint -E
